spring.application.name=product-service
server.port=8082

#spring.data.mongodb.uri=mongodb://localhost:27017/shopflow_product
spring.mongodb.uri=mongodb://localhost:27017/shopflow_product
spring.mongodb.database=shopflow_product

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=product-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

management.endpoints.web.exposure.include=health,info


